### ISSUE TITLE
`threadpoolctl` doesn't seem to do anything with latest NumPy

### ISSUE THREAD

**Issue by itamarst** [joblib/threadpoolctl#121]
Consider the following example from the docs, slightly tweaked to use larger array:

```python
from threadpoolctl import threadpool_limits
import numpy as np

with threadpool_limits(limits=1, user_api="blas"):
    # In this block, calls to blas implementation (like openblas or MKL)
    # will be limited to use only one thread. They can thus be used jointly
    # with thread-parallelism.
    a = np.random.randn(2000, 2000)
    a_squared = a @ a
```

### Evidence, part 1

```shell-session
$ time env OPENBLAS_NUM_THREADS=1 python threadpool.py 
real    0m0.574s
user    0m0.532s
sys     0m0.031s

$ time env OPENBLAS_NUM_THREADS=4 python threadpool.py 
real    0m0.575s
user    0m0.708s
sys     0m0.234s

$ time python threadpool.py 
real    0m0.568s
user    0m0.755s
sys     0m0.178s
```

Notice that with the 4 threads specified via env variable, we get parallelism (`user` CPU is higher than clock time)—and the version with no env variable also has same parallelism, even though we set limit to 1 CPU.

### Evidence, part 2

I update the program as follows:

```python
from threadpoolctl import threadpool_limits
import numpy as np
import psutil

with threadpool_limits(limits=1, user_api="blas"):
    # In this block, calls to blas implementation (like openblas or MKL)
    # will be limited to use only one thread. They can thus be used jointly
    # with thread-parallelism.
    a = np.random.randn(2000, 2000)
    a_squared = a @ a
    print("Num threads:", len(psutil.Process().threads()))
```

And now:

```shell-session
$ python threadpool.py 
Num threads: 4
$ OPENBLAS_NUM_THREADS=1 python threadpool.py 
Num threads: 1
$ OPENBLAS_NUM_THREADS=4 python threadpool.py 
Num threads: 4
```

Same pattern as we see in CPU times: we're getting parallelism even though we used API to limit to a single thread.

**Comment by itamarst** [comment]
```
$ python --version
Python 3.9.7
$ pip list | grep numpy
numpy               1.22.2
$ pip list | grep threadpoolctl
threadpoolctl       3.1.0
```

```
>>> threadpoolctl.threadpool_info()
[{'user_api': 'blas', 'internal_api': 'openblas', 'prefix': 'libopenblas', 'filepath': '/home/itamarst/Devel/memory-profiler/venv/lib/python3.9/site-packages/numpy.libs/libopenblas64_p-r0-2f7c42d4.3.18.so', 'version': '0.3.18', 'threading_layer': 'pthreads', 'architecture': 'Haswell', 'num_threads': 4}]
```

**Comment by jeremiedbb** [comment]
Hi, thanks for the report. When you say with latest numpy, can you provide similar experiment with an older numpy that shows a different behavior ?

Regarding Evidence 2:
the number of threads in openblas threadpool is determined during the first call to openblas and it happens that numpy performs a small blas check at import. So it's expected that the process shows 4 threads when you set the env var because they are created before threadpoolctl is use. Note that it does not mean that threadpoolctl doesn't work, the other threads are just idle.

Regarding Evidence 1:
I tried to reproduce and couldn't achieve the same measurements. I think it would need to be run a few times, say 10, to account for variability, with some wait time between each trial.

**Comment by itamarst** [comment]
Going over the above again, it's a bad experiment, because I'm doing `OPENBLAS_NUM_THREADS` at the same time as `threadpoolctl`, so it's not a good comparison. Further testing where I do one or the other but not both suggests I was wrong. The extra time from multiple CPUs is likely just startup cost, in that it starts multiple threads, but then restricts them later.

My apologies for wasting your time.
